emergency revert to 2.10.3 until 2.11.0 problem sorted out seeing:
"""
which: no jbrowse in (/usr/local/tools/_cache/5d44bb7d/bin:/usr/local/tools/_conda/condabin:/opt/galaxy/venv/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin)
dirname: missing operand
Try 'dirname --help' for more information.
Traceback (most recent call last):
  File "/opt/galaxy/custom-tools/jbrowse2/autogenJB2.py", line 62, in <module>
    jc = jbC(
         ^^^^
  File "/opt/galaxy/custom-tools/jbrowse2/jbrowse2.py", line 420, in __init__
    self.clone_jbrowse()
  File "/opt/galaxy/custom-tools/jbrowse2/jbrowse2.py", line 1538, in clone_jbrowse
    shutil.copytree(self.jbrowse2path, dest, dirs_exist_ok=True)
  File "/usr/local/tools/_cache/5d44bb7d/lib/python3.12/shutil.py", line 586, in copytree
    with os.scandir(src) as itr:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/../opt/jbrowse2'
"""